import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({top,season,manga}) {
  console.log(season);
  console.log(top);
  return (
    <div className="">
      <Head>
        <title>Anilist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-200 w-screen h-auto flex flex-row">
        <div className="flex flex-col w-full">
          <div className="flex flex-wrap justify-between mx-auto items-center w-full h-16 bg-white">
            <h1 className="justify-self-start text-2xl text-black font-thin mx-4">
              Welcome Back!
            </h1>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="w-12 h-12 mx-2"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
              />
            </svg>
          </div>
          <div className="bg-white h-70 mt-10 m-5 rounded-md flex flex-col">
            <h1 className="text-3xl text-black font-thin my-2 mx-4">
              Seasonal Anime
            </h1>
            <div className="flex flex-row overflow-auto ">
              {season.data.map((anime) => (
                <img
                  key={anime.mal_id}
                  src={anime.images.jpg.image_url}
                  width="200"
                  height="auto"
                  className="p-2 rounded-md"
                ></img>
              ))}
            </div>
          </div>
          <div className="flex flex-row">
            <div className="bg-white h-70 w-1/2 m-5 rounded-md flex flex-col">
              <h1 className="text-3xl text-black font-thin my-2 mx-4">
                Top Anime
              </h1>
              <div className="flex flex-row overflow-auto ">
                {top.data.map((anime) => (
                  <img
                    key={anime.mal_id}
                    src={anime.images.jpg.image_url}
                    width="200"
                    height="auto"
                    className="p-2 rounded-md"
                  ></img>
                ))}
              </div>
            </div>
            <div className="bg-white h-70 w-1/2 m-5 rounded-md flex flex-col">
              <h1 className="text-3xl text-black font-thin my-2 mx-4">
                Top Manga
              </h1>
              <div className="flex flex-row overflow-auto ">
                {manga.data.map((anime) => (
                  <img
                    key={anime.mal_id}
                    src={anime.images.jpg.image_url}
                    width="200"
                    height="auto"
                    className="p-2 rounded-md"
                  ></img>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const [topRes, seasonRes, mangaRes] = await Promise.all([
    fetch(`https://api.jikan.moe/v4/seasons/now`), 
    fetch(`https://api.jikan.moe/v4/top/anime`),
    fetch(`https://api.jikan.moe/v4/top/manga`)
  ]);
  const [top, season, manga] = await Promise.all([
    topRes.json(), 
    seasonRes.json(),
    mangaRes.json()
  ]);
  return { props: {season,top,manga} };
  // Pass data to the page via props
}
